#!/usr/bin/env bash
# Generates the Homebrew formula for console-chess from release checksums.
#
# Expects the following environment variables:
#   VERSION          e.g. 1.2.3
#   SHA_MACOS_ARM64  sha256 of chess-<version>-macos-arm64.tar.gz
#   SHA_LINUX_ARM64  sha256 of chess-<version>-linux-arm64.tar.gz
#   SHA_LINUX_X64    sha256 of chess-<version>-linux-x64.tar.gz
#
# Usage:
#   VERSION=1.2.3 \
#   SHA_MACOS_ARM64=... \
#   SHA_LINUX_ARM64=... SHA_LINUX_X64=... \
#   scripts/generate-homebrew-formula.sh > chess.rb
set -euo pipefail

version="${VERSION:?VERSION is required}"
sha_macos_arm64="${SHA_MACOS_ARM64:?SHA_MACOS_ARM64 is required}"
sha_linux_arm64="${SHA_LINUX_ARM64:?SHA_LINUX_ARM64 is required}"
sha_linux_x64="${SHA_LINUX_X64:?SHA_LINUX_X64 is required}"

base="https://github.com/d-led/console-chess/releases/download/v${version}"

cat <<EOF
# typed: false
# frozen_string_literal: true

# This file was generated by d-led/console-chess (scripts/generate-homebrew-formula.sh).
# Do not edit by hand; update via the release workflow or re-run the generator.
class ConsoleChess < Formula
  desc "TUI chess in Java"
  homepage "https://github.com/d-led/console-chess"
  version "${version}"
  license "MPL-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "${base}/console-chess-${version}-macos-arm64.tar.gz"
      sha256 "${sha_macos_arm64}"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "${base}/console-chess-${version}-linux-arm64.tar.gz"
      sha256 "${sha_linux_arm64}"
    else
      url "${base}/console-chess-${version}-linux-x64.tar.gz"
      sha256 "${sha_linux_x64}"
    end
  end

  def install
    bin.install "console-chess"
  end

  test do
    assert_match "Usage: console-chess", shell_output("#{bin}/console-chess --help")
  end
end
EOF
